### PR TITLE
Add seirdy.one

### PR DESCRIPTION
**Pull request by Seirdy**
I'd like to join this webring, provided I can use my own HTML to add the next/prev/home links to my homepage.

### CODE REVIEW

**Comment by Buildstarted** [comment]
Thanks for joining!

**Comment by Seirdy** [comment]
Thanks for having me! I just added the links.

-- 
Seirdy

**Comment by Buildstarted** [comment]
I see the links look correct hope the instructions were clear. Hosting this on github meant I had to make some compromises. For such a small site it didn't seem worth having a full blown host and I think this works well enough for what it is.

**Comment by Seirdy** [comment]
I think it's fine the way it is right now. Everything works like it's 
supposed to.

-- 
Seirdy

**Pull request merged**
